---
- name: Copy sudoers file.
  copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: "0440"
    backup: yes
    validate: "visudo -cf %s"
  register: sudoers_st
  tags:
    - users
    - sudoers

- name: Create shell accounts for SecureDrop admins.
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: sudo,ssh
  with_items: "{{ ssh_users }}"
  tags:
    - users
    - sudoers

- name: Set SecureDrop bash profile additions.
  copy:
    src: bashrc_securedrop_additions
    dest: /etc/profile.d/securedrop_additions.sh
    owner: root
    group: root
    mode: "0644"
  tags:
    - users
    - environment
